### ISSUE TITLE
Dependency versions are not available via pip now

### ISSUE THREAD

**Issue by neeleshkshukla** [microsoft/table-transformer#60]
I was trying to install dependencies via pip  and getting errors. Please upgrade the code and dependencies.

pip3 install pytorch==1.5.0
ERROR: Could not find a version that satisfies the requirement pytorch==1.5.0 (from versions: 0.1.2, 1.0.2)

pip3 install torchvision==0.6.0
ERROR: Could not find a version that satisfies the requirement torchvision==0.6.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0)
ERROR: No matching distribution found for torchvision==0.6.0

**Comment by bsmock** [comment]
Two days ago there was an issue affecting the availability of PyTorch packages for everyone: https://github.com/pytorch/pytorch/issues/81760

Looks like it was resolved. Can you try again now and let us know if you're still running into issues?

**Comment by bsmock** [comment]
Confirmed that the issue with PyTorch packages was temporary and is resolved.

**Comment by neeleshkshukla** [comment]
The issue is still there. 

pip install pytorch==1.5.0 
ERROR: Could not find a version that satisfies the requirement pytorch==1.5.0 (from versions: 0.1.2, 1.0.2)
ERROR: No matching distribution found for pytorch==1.5.0

**Comment by HungVS** [comment]
@neeleshkshukla did you solve the problem?
